### ISSUE TITLE
Suggested renaming of RDF canonicalization spec

### ISSUE THREAD

**Issue by gkellogg** [w3c-ccg/rdf-dataset-canonicalization#2]
From David Booth:

> At present the draft at http://json-ld.github.io/normalization/spec/index.html usually uses the term "normalization" instead of "canonicalization", particularly in the title.  I think it would be clearer if we changed the spec throughout to use the term "canonicalization" instead, because "canonicalization" is more specific and more commonly used for this concept.
> 
> As a data point, the wikipedia entry for "normalization" lists _21_ different senses of the term: http://en.wikipedia.org/wiki/Normalization In contrast, the wikipedia entry for "canonicalization" has only one -- the one we want: http://en.wikipedia.org/wiki/Canonicalization

**Comment by gkellogg** [comment]
I think that one argument for Normalization, vs Canonicalization, is that C14N is often used in different ways for RDF and XML (which will never be completely dis-entangled):

* N-Triples as a Canonical form (as does N-Quads, which we make use of). This is more to do with the syntax of a particular serialization than the notion that two N-Triples documents can be compared purely at a syntactic level.
* XMLLiterals are typically compared using Exclusive XML Canonicalization, which really has to do with the serialization form, rather than an abstract form such as a normalized dataset. 

OTOH, [XMLDSIG](http://www.w3.org/TR/xmldsig-core/) uses the term Canonicalization, and as digital signatures are a primary use case, using similar nomenclature makes sense.

Normalization may be a more “friendly” term for many consumers who probably don’t really care about the mathematical definition, but are more concerned with 

At this point, Normalization may be less overused than canonicalization.

Otherwise, I don’t have a strong opinion, and would go with the consensus.

**Comment by dlongley** [comment]
We debated both names years ago and I don't remember why we went with normalization (yet `c14n` for the prefixes). I think it had to do with the term being used more often, particularly at W3C. Personally, I'd be fine with either, but we should get more input before making a change.

**Comment by lanthaler** [comment]
I'm fine with both. One factor that perhasshould be taken into account is whether the normalized/canocicalized result is expressed in the form of a byte stream or as an abstract RDF graph/set of triples. If it's the former, I think canonicalization might describe it better. If it's the latter, I'd probably slightly prefer normalization.

**Comment by gkellogg** [comment]
The spec describes a type of RDF Dataset (`normalized dataset`) for which blank node identifiers are stable (although wording may not correctly capture that at present). So, in that sense, Normalization may be a better term. Part of the reason for this is that there may be different canonical forms, for example one based on N-Quads and another based on JSON-LD, but these concepts may not survive further scrutiny.

For the purposes of signatures, it is the canonicalized N-Quad form which is the most important; but, for RDF diff, a dataset form may be more useful.

**Comment by brutalcrozt** [comment]
new changes just add more confusion in my opinion, if only JSON-LD which use term normalization and the rest (N-Quads, turtle, N-Triples) use canonicalization. It's okay to use canonicalization, but if not it far better to stay consistent.

**Comment by dbooth-boston** [comment]
@lanthaler canonicalization/normalization MUST be expressed at the byte stream or similar serialization level, because blank node labels do not exist at the abstract RDF level.  They only exist in RDF serializations.  

@brutalcrozt I think it is a trade-off between being consistent with other usage of the terms in many other areas versus being consistent with earlier drafts of the document.  I personally think it is more important to be consistent with other usage than to be bound by early drafts.  Straightening out naming and such is a usual part of the standardization process, in my view.

@gkellogg I don't think it's quite correct to say that the spec defines a type of RDF Dataset, because an RDF Dataset is at the abstract RDF level, not the serialization level: https://www.w3.org/TR/rdf11-datasets/  In contrast, JSON-LD canonicalization/normalization must be expressed at the serialization level, so that blank node labels can be specified and we can use standard diff or cmp tools to find out if two canonicalized/normalized documents describe the same data, rather than requiring special purpose RDF graph matching tools.  (I think it is extremely important to support the use of these standard tools.)

It is true that there could be more than one canonicalization defined, based on different serializations, but I think that is natural because they would be describing different serializations.  I see it as being similar to defining different canonical serializations for body temperature measurements -- one based on CSV, another based on XML, etc.

**Comment by dbooth-boston** [comment]
I just noticed that the wikipedia entry on "canonical form" indicates that a distinction is sometimes made between canonical and normal: 

> "The distinction between "canonical" and "normal" forms varies by subfield. In most fields, a canonical form specifies a unique representation for every object, while a normal form simply specifies its form, without the requirement of uniqueness." -- https://en.wikipedia.org/wiki/Canonical_form

I think this provides more evidence that "canonical" would be a better choice here, to better align with widespread established usage, since a critical point here is to specify a *unique* serialization for an RDF dataset.

**Comment by dlongley** [comment]
I'm in support of "canonicalization" as the name.

**Comment by gkellogg** [comment]
> I don't think it's quite correct to say that the spec defines a type of RDF Dataset, because an RDF Dataset is at the abstract RDF level, not the serialization level ...

As a practical matter, it's quite useful to have something derived from a Dataset that has the property that triples retain their order and Blank Node identifiers are stable, precisely so that we can achieve some form of serialization independence. That promotes the re-use of serializes, as both N-Triples and N-Quads have a [Canonical form](https://www.w3.org/TR/2014/REC-n-triples-20140225/#canonical-ntriples) defined. At some point, there could be a JSON-LD canonical form as well.

I believe the spec can define such a dataset as refinement of an RDF Dataset and be correct, it's just not correct to say that this is the property of an RDF Dataset, as defined in concepts.

Ultimately, for Canonicalization/Normalization to be useful, it must be reduced to a canonical serialization which the spec should define (see #6).
